apiVersion: v1
kind: Namespace
metadata:
  name: monkeyswork
  labels:
    app.kubernetes.io/part-of: monkeyswork
---
apiVersion: v1
kind: Namespace
metadata:
  name: monkeyswork-ai
  labels:
    app.kubernetes.io/part-of: monkeyswork
