apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: monkeyswork-ingress
  namespace: monkeyswork
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: "mw-api-ip"
    networking.gke.io/managed-certificates: "mw-api-cert"
    kubernetes.io/ingress.allow-http: "false"
spec:
  rules:
    - host: api.monkeyswork.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: monkeyswork-api
                port:
                  number: 80
---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: mw-api-cert
  namespace: monkeyswork
spec:
  domains:
    - api.monkeyswork.com
