apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespaces.yaml
  - service-accounts.yaml
  - configmap.yaml
  - network-policies.yaml
  - ingress.yaml
  - hpa.yaml
  - ../ai-scope-assistant/deployment.yaml
  - ../ai-match-v1/deployment.yaml
  - ../ai-fraud-v1/deployment.yaml
  - ../verification-automation/deployment.yaml

commonLabels:
  app.kubernetes.io/managed-by: kustomize
