apiVersion: v1
kind: ServiceAccount
metadata:
  name: ai-scope-assistant
  namespace: monkeyswork-ai
  annotations:
    iam.gke.io/gcp-service-account: mw-ENV-ai-scope@PROJECT_ID.iam.gserviceaccount.com
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ai-match-v1
  namespace: monkeyswork-ai
  annotations:
    iam.gke.io/gcp-service-account: mw-ENV-ai-match@PROJECT_ID.iam.gserviceaccount.com
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ai-fraud-v1
  namespace: monkeyswork-ai
  annotations:
    iam.gke.io/gcp-service-account: mw-ENV-ai-fraud@PROJECT_ID.iam.gserviceaccount.com
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: verification-automation
  namespace: monkeyswork
  annotations:
    iam.gke.io/gcp-service-account: mw-ENV-verification@PROJECT_ID.iam.gserviceaccount.com
